# Quick and dirty and relatively generic Makefile
# Generated by generate_makefile.sh
# By Joel Savitz <jsavitz@redhat.com>

CC 	= gcc
CFLAGS  = -g -Wall -Werror -std=gnu11 -I./lil_test/src
LFLAGS  = -fPIC -shared

OBJECTS = rubix_cube.o monkey.o
TESTOBJ = test_rubix_cube.o
MONKEYO = test_monkey.o

TESTBIN	= test
MONKEYB = test_monkey
LIBNAME = librubix.so

SRCDIR  = src
OBJDIR  = obj

all: $(OBJDIR) $(OBJECTS)
	$(CC) $(LFLAGS) $(CFLAGS) $(patsubst %.o,$(OBJDIR)/%.o, $(OBJECTS)) -o $(LIBNAME)

test: $(OBJDIR) $(OBJECTS) $(TESTOBJ)
	$(CC) $(CFLAGS) $(patsubst %.o,$(OBJDIR)/%.o, $(OBJECTS)) $(patsubst %.o,$(OBJDIR)/%.o, $(TESTOBJ)) -o $(TESTBIN)

test_monkeys: $(OBJDIR) $(OBJECTS) $(MONKEYO)
	$(CC) $(CFLAGS) $(patsubst %.o,$(OBJDIR)/%.o, $(OBJECTS)) $(patsubst %.o,$(OBJDIR)/%.o, $(MONKEYO)) -o $(MONKEYB)

%.o: %.c
	$(CC) $(CFLAGS) -c $^ -o 
.PHONEY: clean $(OBJDIR)
$(OBJDIR):
	mkdir $(OBJDIR)

clean:
	rm -rf $(TESTBIN) $(MONKEYB) $(LIBNAME) $(OBJDIR)

%.o: $(SRCDIR)/%.c
	$(CC) $(LFLAGS) $(CFLAGS) -c $^ -o $(OBJDIR)/$@

